#!/bin/bash
# ══════════════════════════════════════════════════════════════════
# WhisperCUT — One-Token Setup for Claude Code
#
# Usage:
#   curl -sL https://raw.githubusercontent.com/wallpapa/WhisperCUT/main/setup.sh | bash -s YOUR_TOKEN
#
# Example:
#   curl -sL https://raw.githubusercontent.com/wallpapa/WhisperCUT/main/setup.sh | bash -s wcut_76462dadbc25878f207aba60fad779c65985df439fed9a64
# ══════════════════════════════════════════════════════════════════

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

TOKEN="${1}"
SUPABASE_URL="https://yemtipemvgxepafrsxhh.supabase.co"
SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllbXRpcGVtdmd4ZXBhZnJzeGhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwNzAxMzEsImV4cCI6MjA4ODY0NjEzMX0.FA9Twf32a-3tShD2D-qwQ4GIgmBpyIvB30C60YoW7dI"
INSTALL_DIR="$HOME/WhisperCUT"

echo ""
echo "══════════════════════════════════════════════════════"
echo -e "  ${CYAN}🎬 WhisperCUT — AI Video Factory${NC}"
echo "  One-Token Setup for Claude Code"
echo "══════════════════════════════════════════════════════"
echo ""

# ── Validate token ────────────────────────────────────────────────
if [ -z "$TOKEN" ]; then
  echo -e "${RED}❌ Usage: curl -sL https://raw.githubusercontent.com/wallpapa/WhisperCUT/main/setup.sh | bash -s YOUR_TOKEN${NC}"
  echo ""
  echo "  Get your token from the WhisperCUT admin."
  echo ""
  exit 1
fi

if [[ ! "$TOKEN" == wcut_* ]]; then
  echo -e "${RED}❌ Invalid token format. Token must start with 'wcut_'${NC}"
  exit 1
fi

# ── Verify token against Supabase ─────────────────────────────────
echo -e "${YELLOW}🔑 Verifying token...${NC}"
USER_INFO=$(curl -s "$SUPABASE_URL/rest/v1/mcp_users?api_token=eq.$TOKEN&select=email,name,role" \
  -H "apikey: $SUPABASE_ANON_KEY" \
  -H "Authorization: Bearer $SUPABASE_ANON_KEY")

USER_EMAIL=$(echo "$USER_INFO" | grep -o '"email":"[^"]*"' | head -1 | cut -d'"' -f4)
USER_NAME=$(echo "$USER_INFO" | grep -o '"name":"[^"]*"' | head -1 | cut -d'"' -f4)
USER_ROLE=$(echo "$USER_INFO" | grep -o '"role":"[^"]*"' | head -1 | cut -d'"' -f4)

if [ -z "$USER_EMAIL" ]; then
  echo -e "${RED}❌ Invalid token — not found in system${NC}"
  exit 1
fi

echo -e "${GREEN}✅ Welcome, $USER_NAME ($USER_EMAIL) — role: $USER_ROLE${NC}"

# ── Clone / Update ────────────────────────────────────────────────
if [ -d "$INSTALL_DIR/.git" ]; then
  echo -e "${YELLOW}📦 Updating WhisperCUT...${NC}"
  cd "$INSTALL_DIR" && git pull origin main --quiet 2>/dev/null || true
else
  echo -e "${YELLOW}📦 Installing WhisperCUT...${NC}"
  git clone --quiet https://github.com/wallpapa/WhisperCUT.git "$INSTALL_DIR"
  cd "$INSTALL_DIR"
fi

# ── Install + Build ───────────────────────────────────────────────
echo -e "${YELLOW}📦 Installing dependencies...${NC}"
npm install --silent 2>/dev/null
echo -e "${YELLOW}🔨 Building...${NC}"
npx tsc 2>/dev/null
echo -e "${GREEN}✅ Build complete${NC}"

# ── Auto-generate .env ────────────────────────────────────────────
cat > "$INSTALL_DIR/.env" << ENVEOF
# Auto-generated by WhisperCUT setup — $USER_NAME ($USER_EMAIL)
WHISPERCUT_USER_EMAIL=$USER_EMAIL
WHISPERCUT_API_TOKEN=$TOKEN

# Supabase
SUPABASE_URL=$SUPABASE_URL
SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY

# ── AI Provider (ใส่ key ของตัวเอง — เลือก 1 แบบ) ──────────────
# Gemini Free: สมัครที่ https://aistudio.google.com/apikey
# AI_PROVIDER=gemini
# AI_API_KEY=your-key

# Ollama Local: brew install ollama && ollama pull gemma3:27b
AI_PROVIDER=ollama
AI_MODEL=gemma3:27b

# MiniMax TTS (optional)
# MINIMAX_API_KEY=
# MINIMAX_GROUP_ID=
MINIMAX_VOICE_ID=Dr.Gwang

# Video
WHISPER_MODEL=large-v3
FFMPEG_PATH=ffmpeg
OUTPUT_DIR=./output
WHISPERCUT_DATA_DIR=/tmp/whispercut
STUDY_CHANNEL=@doctorwaleerat
ENVEOF
echo -e "${GREEN}✅ .env configured for $USER_EMAIL${NC}"

# ── Configure Claude Code MCP ─────────────────────────────────────
CLAUDE_DIR="$HOME/.claude"
MCP_FILE="$CLAUDE_DIR/.mcp.json"
NODE_PATH=$(which node 2>/dev/null || echo "node")
mkdir -p "$CLAUDE_DIR"

if [ -f "$MCP_FILE" ] && grep -q "whispercut" "$MCP_FILE" 2>/dev/null; then
  echo -e "${GREEN}✅ Claude Code MCP already configured${NC}"
else
  if [ -f "$MCP_FILE" ]; then
    node -e "
      const fs = require('fs');
      const c = JSON.parse(fs.readFileSync('$MCP_FILE','utf-8'));
      if(!c.mcpServers) c.mcpServers={};
      c.mcpServers.whispercut={command:'$NODE_PATH',args:['$INSTALL_DIR/dist/mcp/server.js'],cwd:'$INSTALL_DIR'};
      fs.writeFileSync('$MCP_FILE',JSON.stringify(c,null,2));
    "
  else
    cat > "$MCP_FILE" << MCPEOF
{
  "mcpServers": {
    "whispercut": {
      "command": "$NODE_PATH",
      "args": ["$INSTALL_DIR/dist/mcp/server.js"],
      "cwd": "$INSTALL_DIR"
    }
  }
}
MCPEOF
  fi
  echo -e "${GREEN}✅ Claude Code MCP configured — whispercut registered${NC}"
fi

# ── Status ────────────────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════════════"
echo -e "  ${GREEN}🎬 WhisperCUT พร้อมใช้งานแล้ว!${NC}"
echo ""
echo -e "  ${CYAN}User:${NC}  $USER_NAME ($USER_EMAIL)"
echo -e "  ${CYAN}Role:${NC}  $USER_ROLE"
echo -e "  ${CYAN}AI:${NC}    Ollama (default) — edit .env to change"
echo ""
echo "  👉 Restart Claude Code แล้วลองพิมพ์:"
echo ""
echo "     whispercut_list_vibes"
echo "     whispercut_p2p_status"
echo "     whispercut_vibe_edit topic=\"สมองลูก 3 ขวบ\""
echo ""
echo "  📝 เปลี่ยน AI Provider:"
echo "     nano ~/WhisperCUT/.env"
echo ""
echo "══════════════════════════════════════════════════════"
echo ""
